# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build: .
    restart: on-failure
    volumes: 
      - .:/app
    ports: 
      - 5000:5000
    command: python run.py

  mongo:
    image: mongo:4.4.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: TestDB
    ports: 
      - 27017:27017
    volumes: 
      - ./data:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example